apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }} 
  selector:
    matchLabels:
      app: {{ .Values.backend.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.labels }}
    spec:
      containers:
        - name: multi
          image: {{ .Values.backend.image }}   
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "11443"
          ports:
            - containerPort: 8080
