apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.labels }} 
    spec:
      containers:
        - name: nginx
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: 80
