apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  replicas: 5
  selector:
    matchLabels:
      app: nginxandmulti
  template:
    metadata:
      labels:
        app: nginxandmulti
    spec:
      containers:
        - name: nginx
          image: nginx:1.55
          ports:
            - containerPort: 80
        - name: multi
          image: wbitt/network-multitool:latest
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "11443"
          ports:
            - containerPort: 8080
